export default [
  'A. R. Rahman',
  'Aaron Copland',
  'Alban Berg',
  'André Previn',
  'Andrew Lloyd Webber',
  'Anton Bruckner',
  'Antonin Dvorak',
  'Antonio Carlos Jobim',
  'Antonio Salieri',
  'Antonio Vivaldi',
  'Aphex Twin',
  'Arnold Schoenberg',
  'Arvo Pärt',
  'Astor Piazzolla',
  'Bedřich Smetana',
  'Béla Bartók',
  'Benjamin Britten',
  'Bernard Herrmann',
  'Bix Beiderbecke',
  'Brian Tyler',
  'Burt Bacharach',
  'Caetano Veloso',
  'Camille Saint-Saëns',
  'Carl Maria Von Weber',
  'Carlos Gardel',
  'César Franck',
  'Charles Ives',
  'Clara Schumann',
  'Claude Debussy',
  'Claudio Monteverdi',
  'Cole Porter',
  'Cometan',
  'Count Basie',
  'Danny Elfman',
  'Dave Brubeck',
  'David Diamond',
  'David Foster',
  'Delia Derbyshire',
  'Dmitri Shostakovich',
  'Domenico Scarlatti',
  'Edvard Grieg',
  'Edward Elgar',
  'Ennio Morricone',
  'Eric Whitacre',
  'Erik Satie',
  'Facundo Cabral',
  'Felix Mendelssohn',
  'Frank Zappa',
  'Franz Liszt',
  'Franz Schubert',
  'Frederic Chopin',
  'Gabriel Faure',
  'George Enescu',
  'George Frideric Handel',
  'George Gershwin',
  'Georges Bizet',
  'Giacomo Puccini',
  'Gilbert Bécaud',
  'Gioachino Rossini',
  'Giuseppe Verdi',
  'Goran Bregović',
  'Gustav Holst',
  'Gustav Mahler',
  'Hans Zimmer',
  'Harris Jayaraj',
  'Harry Gregson-Williams',
  'Hector Berlioz',
  'Heitor Villa-Lobos',
  'Henry Mancini',
  'Henry Purcell',
  'Hoagy Carmichael',
  'Howard Shore',
  'Igor Stravinsky',
  'Irving Berlin',
  'Isaac Albéniz',
  'Jacques Brel',
  'James Horner',
  'Jan Hammer',
  'Jean Baptiste Lully',
  'Jean Jacques Rousseau',
  'Jean Michel Jarre',
  'Jean Sibelius',
  'Jean-Philippe Rameau',
  'Jelly Roll Morton',
  'Jerry Goldsmith',
  'Jim Steinman',
  'Jimmy Webb',
  'Joaquin Rodrigo',
  'Joe Hisaishi',
  'Johann Pachelbel',
  'Johann Sebastian Bach',
  'Johannes Brahms',
  'John Barry',
  'John Cage',
  'John Dowland',
  'John Philip Sousa',
  'John Powell',
  'John Rutter',
  'John Tavener',
  'John Tesh',
  'John Williams',
  'John Zorn',
  'Joseph Haydn',
  'Juventino Rosas',
  'Karl Jenkins',
  'Karlheinz Stockhausen',
  'Klaus Badelt',
  'Klaus Schulze',
  'Koji Kondo',
  'Krzysztof Penderecki',
  'Kurt Weill',
  'La Monte Young',
  'Laurie Anderson',
  'Leonard Bernstein',
  'Ludovico Einaudi',
  'Ludwig Van Beethoven',
  'Manuel De Falla',
  'Marvin Hamlisch',
  'Maurice Ravel',
  'Michael Giacchino',
  'Michael Kamen',
  'Michael Nyman',
  'Michel Camilo',
  'Michel Legrand',
  'Mike Oldfield',
  'Mikis Theodorakis',
  'Niccolò Paganini',
  'Nile Rodgers',
  'Nino Rota',
  'Nobuo Uematsu',
  'Olivier Messiaen',
  'Patrick Doyle',
  'Paul Desmond',
  'Philip Glass',
  'Pierre Boulez',
  'Pyotr Ilyich Tchaikovsky',
  'R. D. Burman',
  'Ralph Vaughan Williams',
  'Ramin Djawadi',
  'Richard Strauss',
  'Richard Wagner',
  'Robert Schumann',
  'Ryuichi Sakamoto',
  'Samuel Barber',
  'Scott Joplin',
  'Sergei Prokofiev',
  'Sidney Bechet',
  'Stephen Sondheim',
  'Steve Jablonsky',
  'Steve Morse',
  'Steve Reich',
  'Terry Riley',
  'Thelonious Monk',
  'Thomas Tallis',
  'Tom Zé',
  'Vishal Bhardwaj',
  'W. C. Handy',
  'William Byrd',
  'Wim Mertens',
  'Wolfgang Amadeus Mozart',
  'Yanni',
  'Yoko Kanno',
  'Yuvan Shankar Raja',
  'Zeca Afonso',
];
